easytimetable/events/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('events.views',
    (r'^$', 'display_calendar', {}, 'display_calendar'),
    (r'^mobile/$', 'list_events', {}, 'list_events'),
    (r'^users/me/$', 'get_planning', {'what' : 'me'}, 'get_own_planning'),
    (r'^test/$', 'get_planning', {'what' : 'test'}, 'get_test_planning'),

    #(r'^users/(?P<user_id>\d+)$', 'get_planning', {'what' : 'user'}, 'get_user_planning'),
    (r'^user/add/$', 'add_user_event', {}, 'add_user_event'),
    (r'^move/(?P<when_id>\d+)?$', 'move_event', {}, 'move_event'),
    (r'^resize/(?P<when_id>\d+)?$', 'resize_event', {}, 'resize_event'),
    
    (r'^get/(?P<what>\w+)?(/?(?P<what_arg>\d+)?)?$', 'get_planning', {}, 'get_planning'),
    (r'^ical/(?P<what>\w+)?(/?(?P<what_arg>\d+)?)?$', 'get_ical', {}, 'get_ical'),
    (r'^add/(?P<what>\w+)?(/?(?P<what_arg>\d+)?)?$', 'add_event', {}, 'add_event'),
    (r'^update/(?P<when_id>\d+)?$', 'update_event', {}, 'update_event'),
    (r'^delete/(?P<when_id>\d+)?$', 'delete_event', {}, 'delete_event'),
)

easytimetable/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    
    (r'^$', 'django.views.generic.simple.direct_to_template', {
        'template': 'presentation/plaquette.html',
    }, 'index'),
    (r'^admin/', include(admin.site.urls)),
    (r'^pedagogy/', include('pedagogy.urls', namespace='pedagogy')),
    (r'^events/', include('events.urls', namespace='events')),
    (r'^locations/', include('locations.urls', namespace='locations')),
    (r'^profiles/', include('profiles.urls', namespace='profiles')),
    (r'^ical/', include('ical.urls', namespace='ical')),
    
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {}, 'login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {}, 'logout'),
)

# To serve static files. Do not use in production
if settings.SERVE_STATIC_FILES:
    urlpatterns += patterns('', 
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', 
            {'document_root': settings.MEDIA_ROOT}),
    )

easytimetable/events/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.core.exceptions import ObjectDoesNotExist
import copy

from managers import WhenManager
from locations.models import Place, Campus, University
from vobject.icalendar import Component, dateTimeToString

class When(models.Model):
    date = models.DateTimeField(blank=True, default=datetime.datetime.now)
    event = models.ForeignKey('Event')
    objects = WhenManager()
    
    def __unicode__(self):
        return self.date.strftime('%d-%B-%Y')

    def to_vevent(self):
        vevent = Component('vevent')
        vevent.add('dtstart').value = dateTimeToString(self.date)
        vevent.add('dtstamp').value = dateTimeToString(datetime.datetime.now())
        vevent.add('dtend').value = dateTimeToString(self.date +\
                datetime.timedelta(hours=self.event.duration))
        vevent.add('summary').value = self.event.name
        try:
            place = "%s : %s" % (self.event.places.get().name,
                                  self.event.places.get().address)
        except ObjectDoesNotExist:
            place = self.event.place_text
        vevent.add('location').value = place
        return vevent
    
    def to_fullcalendar_dict(self, is_editable=lambda when:False,
    css_class='undef'):
        """Return this object under a FullCalendar compatible dict format.

        The is_editable callable is called with the 

        """
        dct = { 'title' : self.event.name,
                'id' : self.id,
                'event_id': self.event_id,
                'allDay' : False,
                'start' : self.date.isoformat(),
                'end' : (self.date +
                datetime.timedelta(hours=self.event.duration)).isoformat(),
                'editable' : is_editable(self),
                'className' : css_class,
            }
        return dct

    


class Who(models.Model):
    """The Who model has some references to different others models.

    To know who is concerned by an event, it have a method that return this
    informations.
    """
    event = models.ForeignKey('Event')
    user = models.ForeignKey(User, null=True, blank=True)
    classgroup = models.ForeignKey('profiles.ClassGroup', null=True, blank=True)
    cursus = models.ForeignKey('pedagogy.Cursus', null=True, blank=True)
    campus = models.ForeignKey('locations.Campus', null=True, blank=True)
    university = models.ForeignKey('locations.University', null=True, blank=True)
    is_contributor = models.BooleanField(default=False)

    # set to true if it concerns everyone.
    is_universal = models.BooleanField(default=False)

class Event(models.Model):
    name = models.CharField(blank=False, max_length=150)
    duration = models.PositiveIntegerField(blank=False, null=False)
    places = models.ManyToManyField('locations.Place', null=True, blank=True)
    subject_modality = models.ForeignKey('pedagogy.SubjectModality', null=True,
    blank=True)
    force_display = models.BooleanField(default=False)
    place_text = models.CharField(max_length=255, blank=True)
    
    def get_type(self):
        #Define the priorities here
        types = {"campus" : 0,
                "classgroup" : 0,
                "university" : 0,
                "user" : 0}
        res = copy.deepcopy(types)
        who_set = self.who_set.filter(is_contributor=False).all()
        for who in who_set:
            for type, score in types.iteritems():
                if hasattr(who, type):
                    if getattr(who, type) is not None:
                        types[type] = score + 1
                        res[type]=who
        return (max(types,key=types.get), res[max(types,key=types.get)])
        
    def __unicode__(self):
        return self.name

easytimetable/events/views.py
"""List of django views for planning management

"""
# django imports
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils import simplejson as json
from django.core.exceptions import ObjectDoesNotExist

# python imports
import functools
from datetime import date, datetime, timedelta
from vobject import iCalendar

# app imports
from events.models import When, Who, Event
from pedagogy.models import SubjectModality
from utils.shortcuts import render_to_response
from events.forms import UserEventForm, CampusEventForm, ClassgroupEventForm,\
MoveEventForm, ClassgroupSelectorForm, CampusSelectorForm, MySelectorForm
from events.managers import WhenManager
    
def is_event_editable(user, when):
    event_type, who = when.event.get_type()
    if event_type == 'classgroup' and\
        user.get_profile().can_manage_classgroup(who.classgroup.id):
        return True
    if event_type == 'user' and who.user == user:
        return True
    if event_type == 'campus' and\
        user.get_profile().can_manage_campus(who.campus.id):
        return True
    return False
    
@login_required
def get_planning(request, what=None, what_arg=None, extra_context={}, **kwargs):
    """Return the planning for `what`. What determines the method we will use
    to fetch the informations through the model manager.

    Special parameters can be set in `extra_parameters`.
    This mainly return the JSON to be parsed by the calendar client.

    """
    start_date = date.fromtimestamp(int(request.GET["start"]))
    end_date = date.fromtimestamp(int(request.GET["end"]))
    #We don't want people to make too big queries

    if (end_date - start_date).days > 50:
        end_date = start_date

    # partial to not give the request to the model.
    partial_is_editable = functools.partial(is_event_editable, request.user)
    w = When.objects.user_planning(request.user, what, start_date, end_date,\
    what_arg)
    if what == "classgroup":
        what = "%s-%s" % (what, int(what_arg) % 5)
    d = [p.to_fullcalendar_dict(partial_is_editable, what) for p in w]
    return HttpResponse(json.dumps(d))

def get_ical(request, what=None, what_arg=None, must=True, extra_context={}, **kwargs):
    start_date = date.min
    end_date = date.max
    w = When.objects.user_planning(request.user, what, start_date, end_date,\
    what_arg)
    cal = iCalendar()
    cal.add('method').value = 'PUBLISH'  # IE/Outlook needs this
    for e in w:
        cal.add(e.to_vevent())
    icalstream = cal.serialize()
    response = HttpResponse(icalstream, mimetype='text/calendar')
    if what_arg is None:
        what_arg = ""
    response['Filename'] = '%s%s.ics' % (what, what_arg)  # IE needs this
    response['Content-Disposition'] = 'attachment; filename=%s' %\
        response['Filename']
    return response


@login_required
def list_events(request):
    to_fetch = ("mandatory", "my_user", "my_classgroup", "my_campus",
    "my_university")
    events = set()
    start_date = datetime.now()
    end_date = datetime.now()+timedelta(days=7)
    for source in to_fetch:
        fetched = When.objects.user_planning(request.user, source,
                                         start_date, end_date)
        for event in list(fetched):
            event.resource = source
        events = events | set(fetched)
    return render_to_response('list_events.html', {'whens' : events,} , request)

        

@login_required
def add_event(request, what=None, what_arg=None, extra_context={}, **kwargs):
    if what == "classgroup":
        return add_classgroup_event(request)
    if what == "campus":
        return add_campus_event(request)
    if what == "my_user":
        return add_user_event(request)
    if what == "my_university":
        pass

@login_required
def add_user_event(request):
    if request.POST:
        form = UserEventForm(data=request.POST, prefix="user")
        if form.is_valid():
            when = form.save()
            who = Who(user=request.user, event=when.event)
            who.save()
            j = when.to_fullcalendar_dict(lambda when:True, "my_user")
            return HttpResponse(json.dumps(j))
        else:
            return False

@login_required
def move_event(request, when_id):
    if request.POST:
        when = When.objects.get(id=when_id)
        if not is_event_editable(request.user, when):
            return False
        form = MoveEventForm(data=request.POST)
        if form.is_valid():
            offset = timedelta(days=form.cleaned_data['days'],
                                minutes=form.cleaned_data['minutes'])
            n_date = when.date + offset
            when.date = n_date
            when.save()
            j = when.to_fullcalendar_dict(lambda when:True, "moved")
            return HttpResponse(json.dumps(j))
        else:
            return False

@login_required
def resize_event(request, when_id):
    if request.POST:
        when = When.objects.get(id=when_id)
        if not is_event_editable(request.user, when):
            return False
        form = MoveEventForm(data=request.POST)
        if form.is_valid():
            duration = int(form.cleaned_data['days']) * 24 +\
                       int(form.cleaned_data['minutes']) / 60
            when.event.duration = when.event.duration + duration
            when.event.save()
            return HttpResponse("ok")
        else:
            return HttpResponse("!ok")

@login_required
def delete_event(request, when_id):
    if request.POST:
        when = When.objects.get(id=when_id)
        if not is_event_editable(request.user, when):
            return HttpResponse("!ok", status=403)
        when.event.delete()
        return HttpResponse("ok")
    return HttpResponse("!ok", status=500)

@login_required
def display_calendar(request):
    #Standard forms
    user_form = UserEventForm(prefix="user")
    my_selector_form = MySelectorForm(prefix="my_selector")
    forms = { 'user_form': user_form,}
    selectors = {'my_selector_form': my_selector_form,}

    if request.user.get_profile().can_manage_campus():
        forms['campus_form'] = CampusEventForm(prefix="campus",
            user=request.user)
        forms['classgroup_form'] = ClassgroupEventForm(prefix="classgroup",
            user=request.user)
        selectors['campus'] = CampusSelectorForm(
            prefix="cmp_selector", user=request.user)
        selectors['classgroup'] = ClassgroupSelectorForm(
            prefix="cg_selector", user=request.user)
        selectors['my_selector_form'] = MySelectorForm(prefix="my_selector",
            what=["my_user"])

    forms.update(selectors)
    return render_to_response('calendar.html', {'forms' : forms,} , request)

    

@login_required
def display_campus_mgr_calendar(request):
    user_form = UserEventForm(prefix="user")
    my_selector_form = MySelectorForm(prefix="my_selector", what=["my_user"])
    return render_to_response('calendar.html', {
        'campus_form': campus_form, 
        'user_form': user_form, 
        'classgroup_form': classgroup_form, 
        'classgroup_selector_form': classgroup_selector_form,
        'campus_selector_form': campus_selector_form,
        'my_selector_form': my_selector_form,
    }, request)


@login_required
def add_classgroup_event(request):
    if request.POST:
        form = ClassgroupEventForm(user=request.user, data=request.POST,
                                   prefix="classgroup")
        when = form.save()
        j = when.to_fullcalendar_dict(lambda when:True, "classgroup")
        return HttpResponse(json.dumps(j))
    else:
        return False

@login_required
def add_campus_event(request):
    if request.POST:
        form = CampusEventForm(user=request.user, data=request.POST,
                                   prefix="campus")
        when = form.save()
        j = when.to_fullcalendar_dict(lambda when:True, "campus")
        return HttpResponse(json.dumps(j))
    else:
        return False

def update_event(request, when_id):
    form = None
    when = get_object_or_404(When, pk=when_id)
    event_type, who = when.event.get_type()
    data = {'name' : when.event.name,
            'date' : when.date.strftime("%Y-%m-%d"),
            'start_hour' : int(when.date.strftime("%H")),
            'duration' : int(when.event.duration),
            'place_text' : when.event.place_text,
            'force_display' : when.event.force_display,
           }
    if event_type == 'classgroup' and\
            request.user.get_profile().can_manage_classgroup(who.classgroup.id):
        data.update({'place' : when.event.places.get().id,
             'classgroup' :
             who.classgroup.id,
             'modality' : 
             when.event.subject_modality.type,
             'subject' : 
             when.event.subject_modality.subject.id, })
        if request.POST:
            form = ClassgroupEventForm(user=request.user, data=request.POST)
        else:
            form = ClassgroupEventForm(user=request.user, initial=data)
    elif event_type == 'user' and\
            who.user == request.user:
        if request.POST:
            form = UserEventForm(data=request.POST)
        else:
            form = UserEventForm(initial=data)
    elif event_type == 'campus' and\
            request.user.get_profile().can_manage_cursus(who.campus.id):
        try:
            place_id = when.event.places.get().id
        except ObjectDoesNotExist:
            place_id = None
        data.update({'place' : place_id,
                     'campus' : who.campus.id,
                     })
        if request.POST:
            form = CampusEventForm(data=request.POST, user=request.user)
        else:
            form = CampusEventForm(initial=data, user=request.user)
    if request.POST:
        if form.is_valid():
            when = form.save(when)

easytimetable/events/templates/calendar.html
{% extends "base_fullcalendar.html" %}
{% load i18n %}
{% load uni_form_tags %}
{% block fullcalendar_init %}
<script type="text/javascript"> 
calendar = null;
calendar_manager = null;

$(document).ready(function(){
    var calendar = $('#calendar').fullCalendar({
        header: {
            center: 'title',
            left: 'month,agendaWeek,agendaDay',
            right: 'prev,next today',
        },
        theme: true,
        selectable: true,
        selectHelper: true,
        editable: true,
        firstHour: 8,
        select: function(start, end, allDay) {
           pop_add_event_dialog(start, end, allDay);

        },
        eventClick: function(calEvent, jsEvent, view) {
            if(calEvent.editable)
                pop_edit_event_dialog(calEvent.id, jsEvent);
        },
        eventDrop: function(calEvent, days, minutes, allDay) {
            $.post("{% url events:move_event %}"+calEvent.id,
            {"days" : days, "minutes" : minutes, "all_day": allDay});
        },
        eventResize: function(calEvent, days, minutes) { 
            $.post("{% url events:resize_event %}"+calEvent.id,
            {"days" : days, "minutes" : minutes, "all_day": false}
            );
        },
    });
    
    calendar_manager = new CalendarManager($('#calendar'), 
    "{% url events:display_calendar %}");
    //Calendar Selectors declaration
    $('#my_selector :checkbox').each(function(){
        new CalendarCheckbox($(this), calendar_manager);
    });
    $('#campus_selector :checkbox').each(function(){
        new CalendarCheckbox($(this), calendar_manager, "campus");
    });
    $('#classgroup_selector :checkbox').each(function(){
        new CalendarCheckbox($(this), calendar_manager, "classgroup");
    });
    init_forms();

    // automatically load ajax links within a modal dialog box
    $('a.ajax').click(function(){return pop_add_event_dialog(null,null,null);});
});


function pop_add_event_dialog(start, end, allDay)
{
    $("#add_event_dialog").dialog({
        modal: true,
        open: function(){$("#tabs").tabs(); init_all_forms(start, end, allDay);},
        width: 500,
        height: 500,
        title: "{% trans "Add an event" %}",
    });
    return false;
}

function pop_edit_event_dialog(event_id)
{
    $("#edit_event_dialog").dialog({
        modal: true,
        open: function(){$.get("{% url events:update_event %}" + event_id,
            function(data){$("#edit_event_form_div").html(data);
                           $("#edit_event_form_div .datepicker").datepicker({dateFormat: 'yy-mm-d'});
                           $("#form_edit_event").data("edit_url","{% url events:update_event %}"), +
                           $("#form_edit_event").data("delete_url","{% url events:delete_event %}"), +
                           $("#form_edit_event").data("event_id", event_id);})},
        title: "{% trans "Edit an event" %}",
        width: 500,
        height: 500,
    });
    return false;
}

function update_classgroup_event_name()
{
    new_name = $('#id_classgroup-subject option:selected').text() + ' : ' +
               $('#id_classgroup-modality option:selected').text();
    $('#id_classgroup-name').val(new_name);
}

function init_all_forms(start, end, allDay){
    start_date = formatDate(parseDate(start), "yyyy-MM-dd");
    start_hour = formatDate(parseDate(start), "HH")-0;
    end_hour = formatDate(parseDate(end), "HH")-0;
    duration = end_hour - start_hour;

    preload_classgroup_form(start_date, start_hour, duration);
    preload_campus_form(start_date, start_hour, duration);
    preload_user_form(start_date, start_hour, duration);
    
}

function init_forms(){
    $('#id_classgroup-subject').change(function() {
                                update_classgroup_event_name()});
    $('#id_classgroup-modality').change(function() {
                                update_classgroup_event_name()});

    //First : we load the subjects
    $('#id_classgroup-classgroup').change(function(){
        if($("#id_classgroup-classgroup").val()=="")
            return false;
        $.getJSON("{% url profiles:list_classgroups %}" +
        $("#id_classgroup-classgroup").val() +
                "/subjects/", null, function(data) {
                $('#id_classgroup-subject').empty();
                for(line in data)
                {
                    itemData = data[line];
                    var option = new Option(itemData['name'], itemData['id']);
                    $('#id_classgroup-subject').append(option);
                }
            }
    );
    });

    //Then we change the submit system

    new CalendarSubmiter($('#form_add_classgroup_event'), calendar_manager,
        "classgroup", function() {$('#add_event_dialog').dialog('close');});
    new CalendarSubmiter($('#form_add_campus_event'), calendar_manager,
        "campus", function() {$('#add_event_dialog').dialog('close');});
    new CalendarSubmiter($('#form_add_user_event'), calendar_manager,
        "my_user", function() {$('#add_event_dialog').dialog('close');});
    new CalendarEditor($('#form_edit_event'), calendar_manager, function(){
        $('#edit_event_dialog').dialog('close');});
    calendar_manager.add_event_source("mandatory", "");
    calendar_manager.display_event_source("mandatory");
        
}

function preload_classgroup_form(start_date, start_hour, duration){
    //Then we set the selected class
    $('#id_classgroup-classgroup').val($("#id_cg_selector-classgroup").val());
    //Then we set the date
    $('#id_classgroup-date').val(start_date);
    $('#id_classgroup-start_hour').val(start_hour);
    $('#id_classgroup-duration').val(duration);
    
    update_classgroup_event_name();
}

function preload_campus_form(start_date, start_hour, duration){
    //Then we set the selected class
    $('#id_campus-campus').val($("#id_cmp_selector-campus").val());
    //Then we set the date
    $('#id_campus-date').val(start_date);
    $('#id_campus-start_hour').val(start_hour);
    $('#id_campus-duration').val(duration);
}

function preload_user_form(start_date, start_hour, duration){
    //Then we set the date
    $('#id_user-date').val(start_date);
    $('#id_user-start_hour').val(start_hour);
    $('#id_user-duration').val(duration);
}

</script>
{% endblock %}
{% block content %}
<p class="info">{% trans "Here you can <strong>view, add or edit the different plannings</strong>, depending on the rights you have. Click on the calendar to create a new event on your agenda !" %}</p>
<div id='calendar'></div> 

<div id="edit_event_dialog" style="display: none;">
    <form id="form_edit_event">
        <div id="edit_event_form_div"></div>
        <div class="right">
            <input type="submit" value="{% trans "update" %}" class="awesome green"/>
            <input type="button" name="deleter" class="awesome red" value="{% trans "delete" %}"/>
        </div>
    </form>
</div>

<div id="add_event_dialog" style="display: none;">
    <div id="tabs">
    <ul>
        {% if forms.classgroup_form %}
            <li><a href="#fragment-1"><span>Class</span></a></li>
        {% endif %}
        {% if forms.campus_form %}
            <li><a href="#fragment-2"><span>Campus</span></a></li>
        {% endif %}
            <li><a href="#fragment-3"><span>My events</span></a></li>
    </ul>
    {% if forms.classgroup_form %}
        <div id="fragment-1">
            <form id="form_add_classgroup_event">
               {{forms.classgroup_form.as_p}}
               <input type="submit" id="sub-classgroup_event" value="-->"/>
            </form>
        </div>
    {% endif %}
    {% if forms.campus_form %}
        <div id="fragment-2">
            <form id="form_add_campus_event">
                {{forms.campus_form.as_p}}
                <input type="submit" id="sub-campus_event" value="-->"/>
            </form>
        </div>
    {% endif %}
        <div id="fragment-3">
            <form id="form_add_user_event">
                {{forms.user_form.as_p}}
                <input type="submit" id="sub-user_event" value="-->"/>
            </form>
        </div>
    </div>
</div>


{% endblock %}
{% block menu %}
    <div id="menu" class="span-4 last">
    <form name="campus" id="campus_selector" class="calendar_selector"> 
        {{ forms.campus.as_p }}
    </form>
    <form id="classgroup_selector" class="calendar_selector"> 
        {{ forms.classgroup.as_p }}
    </form>
    <form id="my_selector" class="calendar_selector"> 
        {{ forms.my_selector_form.as_p }}
    </form>
    </div>
{% endblock %}

easytimetable/events/templates/edit_user_calendar.html
{% load uni_form_tags %}
{{form|as_uni_form}}

easytimetable/events/templates/list_events.html
{% extends "base.html" %}
{% load i18n %}
{% load uni_form_tags %}
{% block content %}
<p class="info">{% trans "You can find here the events for the next seven days." %}</p>

{% if whens %}
<ul id="eventlist">
{% for when in whens|dictsort:"date" %}
    {% ifchanged %}<h3>{{ when.date|date:"l F d"}}</h3>{% endifchanged %}
    <li class="{{ when.resource }} {% cycle "even" "odd" %}">
        {{ when.date|time:"H:i" }} --  <span class="event_name">{{ when.event.name }} </span>
        {% trans "for" %} {{ when.event.duration }} {% trans "hour(s)" %}.
    </li>
{% endfor %}
</ul>
{% else %}
<br />
{% blocktrans %}You don't have any events, yet.{% endblocktrans %}
{% endif %}
{% endblock %}